---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr/config:/config
      - "${PLEX_LIBRARY_PATH}:/Plex"
      - "${QBITTORRENT_DOWNLOAD_PATH}:/downloads"
    ports:
      - "8989:8989"
    restart: unless-stopped


  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
#      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett-config:/config
      - "${PLEX_LIBRARY_PATH}:/downloads"
    ports:
      - "9117:9117"
    restart: unless-stopped


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - "${QBITTORRENT_DOWNLOAD_PATH}:/downloads"
      - "${PLEX_LIBRARY_PATH}:/Plex"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./radarr/config:/config
      - "${PLEX_LIBRARY_PATH}:/Plex"
      - "${QBITTORRENT_DOWNLOAD_PATH}:/downloads"
    ports:
      - "7878:7878"
    restart: unless-stopped