#!/usr/bin/env bash

set -e

DEFAULT_NETWORK_VOLUME_PATH="/Volumes/SG WD 2TB S"
DEFAULT_QBITTORRENT_DOWNLOAD_PATH="/Users/stephengeller/Downloads/Torrents/qbittorrent"

export NETWORK_VOLUME_PATH=${1:-${DEFAULT_NETWORK_VOLUME_PATH}}
export QBITTORRENT_DOWNLOAD_PATH=${2:-${DEFAULT_QBITTORRENT_DOWNLOAD_PATH}}

echo NETWORK_VOLUME_PATH: "$NETWORK_VOLUME_PATH"
echo QBITTORRENT_DOWNLOAD_PATH: "$QBITTORRENT_DOWNLOAD_PATH"

# Check that the drive is mounted
if ! (mount | grep "on ${NETWORK_VOLUME_PATH}" > /dev/null); then
    echo -e "\033[31;1mERROR: \033[0;31mPlease mount the external drive to ${NETWORK_VOLUME_PATH}\033[0m"
    exit 1
fi

if [ ! -d "$QBITTORRENT_DOWNLOAD_PATH" ]; then
  echo -e "\033[31;1mERROR: \033[0;31mTemporary download path ${QBITTORRENT_DOWNLOAD_PATH} does not exist\033[0m"
  exit 1
fi

# Spin up services
sudo NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" QBITTORRENT_DOWNLOAD_PATH="${QBITTORRENT_DOWNLOAD_PATH}" docker-compose up -d --force-recreate --build