#!/usr/bin/env bash

set -eo pipefail

PWD="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

. "${PWD}"/source-vars $1 $2

# Check that all mounted volumes have correct permissions
# sudo chmod 777 ~/Downloads/Torrents/qbittorrent

# Spin up services
sudo NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" \
  QBITTORRENT_DOWNLOAD_PATH="${QBITTORRENT_DOWNLOAD_PATH}" \
  docker-compose up -d

# Open websites
#open http://localhost:8989
#open http://localhost:9117
#open http://localhost:8080