#!/usr/bin/env bash

set -e

NETWORK_VOLUME_PATH=${1:-"/Volumes/SG WD 2TB S"}

# Check that the drive is mounted
if ! (mount | grep "on ${NETWORK_VOLUME_PATH}" > /dev/null); then
    echo -e "\033[31;1mERROR: \033[0;31mPlease mount the external drive to ${NETWORK_VOLUME_PATH}\033[0m"
    exit 1
fi

# Check that all mounted volumes have correct permissions
# sudo chmod 777 ~/Downloads/Torrents/qbittorrent

# Spin up services
NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" docker-compose up -d

# Open websites
#open http://localhost:8989
#open http://localhost:9117
#open http://localhost:8080