#!/usr/bin/env bash

set -e

PWD="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

. "${PWD}"/source-vars

# Turn off services
sudo NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" \
  QBITTORRENT_DOWNLOAD_PATH="${QBITTORRENT_DOWNLOAD_PATH}" \
  docker-compose down