#!/usr/bin/env bash

set -e

# Turn off services
# We're putting /tmp as the path so you don't have to pass them as args
# just to stop the containers
sudo PLEX_LIBRARY_PATH="/tmp" QBITTORRENT_DOWNLOAD_PATH="/tmp" docker-compose down